### ISSUE TITLE
Generate BEAT data 

### ISSUE THREAD

**Issue by Bastard007** [ch-apps/player#4]
How i can generate BEAT data of my music? Autogeneration does not work.

P.S. Sorry for my bad english )))

**Comment by ch-apps** [comment]
Check the documentation https://github.com/ch-apps/player/blob/main/docs/MANUAL.md#beatfile 
There are 2 types of BeatFiles which could be read by the player (SIMPLE and with exact  TIMESTAMPS). You must create a BeatFile to each audio file. Based on this the player generates the beat-meter (either autoerated based on BPM in case of SIMPLE format used, or exactly as is defined by timestamps in the second format). 
Check out examples in https://github.com/ch-apps/player/tree/main/AV_MEDIA/AUDIO/Test directory.
